name: Expressions and Contexts
on: [push, pull_request, issues, workflow_dispatch]
# we can customize the title that appears in the wf run
# using run-name key. we use context to dynamically create a title for our run
run-name: "Expressions and Contexts by @${{ github.actor }}, event: ${{ github.event_name }}"
jobs:
    using-expressions-and-contexts:
        runs-on: ubuntu-latest
        steps:
            - name: Expressions
              id: expression
              run: |
                echo ${{ 1 }}
                echo "${{ 'this is a string' }}"
                echo ${{ null }}
                echo ${{ true }}
                echo ${{ 1 > 2 }}
                echo ${{ 'string' == 'String' }}
                echo ${{ true && false }}
                echo ${{ true || (false && true) }}
            - name: Dump Contexts
            # toJson() is a function
            # we use ${{}} in github for defining expressions, variables, and context values within WFs
            # it is used for dynamically reference data and execute commands based on certain commands or inputs
            # github, job, secrets, steps, runner, matrix, vars, needs, strategy, env are called objects or contexts.
              run: |
                echo '${{ toJson(github) }}''
                echo "${{ toJson(job) }}"
                echo "${{ toJson(secrets) }}"
                echo "${{ toJson(steps) }}"
                echo "${{ toJson(runner) }}"


