# environment variable can only be used in the workflow where they are defined. we cannot use them in other workflow
# configuration variables: configuration variables can be available for all workflows in our repository and for multiple repositories in our organization
# we will define the configurstion variables in organization level or repository level or environment level 
# we can define configuration variables and secrets inside the environment
# secrets are encripted variables are not encripted. we use secrets to store sensitive information
# we can also set secrets and variables in the repository level and organization level path--in repository>>setings>>secrets and variables>>actions>> where you can define environment, repository and organizational level vars and secrets
# 
 
name: Variables and Secrets
on: [push]

jobs:
    log-vars:
        runs-on: ${{vars.JOBS_RUNNER}}
        env:
            BOOLEAN_SECRET: ${{secrets.BOOLEAN_SECRET}}
            ENV_LEVEL_VAR: ${{vars.ENV_LEVEL_VAR}}
            REPO_LEVEL_VAR: ${{vars.REPO_LEVEL_VAR}}
            ORG_LEVEL_VAR: ${{vars.ORG_LEVEL_VAR}}
        steps:
            - name: runs only if the boolean secret is true
              if: ${{env.BOOLEAN_SECRET=='true'}}
              run: echo "i ran"
            - name: log vars
              run: |
                echo "${{vars.JOBS_RUNNER}}"
                echo "ENV_LEVEL_VAR: $ENV_LEVEL_VAR"
                echo "REPO_LEVEL_VAR: $REPO_LEVEL_VAR"
                echo "ORG_LEVEL_VAR: $ORG_LEVEL_VAR"